# Generated by Django 3.0.8 on 2020-07-06 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aliment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('created_at', models.DateField()),
                ('updated_at', models.DateField()),
                ('expires_at', models.DateField()),
                ('stockreading', models.CharField(max_length=20)),
            ],
        ),
    ]
